# Generated by Django 5.2.7 on 2025-11-04 05:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='渠道的显示名称', max_length=100, verbose_name='渠道名称')),
                ('type', models.CharField(choices=[('bark', 'Bark'), ('ntfy', 'Ntfy'), ('email', 'Email'), ('feishu', '飞书')], help_text='选择通知渠道类型', max_length=20, verbose_name='渠道类型')),
                ('config', models.JSONField(default=dict, help_text='JSON格式的渠道配置信息', verbose_name='渠道配置')),
                ('enabled', models.BooleanField(default=True, help_text='是否启用该渠道', verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '通知渠道',
                'verbose_name_plural': '通知渠道',
                'db_table': 'chewy_notify_channel',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alias', models.CharField(help_text='通知目标的显示名称', max_length=100, verbose_name='目标别名')),
                ('target_type', models.CharField(choices=[('bark_token', 'Bark Token'), ('email', 'Email地址'), ('ntfy_topic', 'Ntfy主题'), ('feishu_webhook', '飞书Webhook')], help_text='通知目标的类型', max_length=20, verbose_name='目标类型')),
                ('target_value', models.CharField(help_text='具体的通知目标值（如邮箱、token等）', max_length=500, verbose_name='目标值')),
            ],
            options={
                'verbose_name': '通知目标',
                'verbose_name_plural': '通知目标',
                'db_table': 'chewy_notify_target',
                'ordering': ['-create_time'],
                'unique_together': {('target_type', 'target_value')},
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='模板的唯一标识名称', max_length=100, unique=True, verbose_name='模板名称')),
                ('title', models.CharField(help_text='通知标题，支持变量替换', max_length=200, verbose_name='标题模板')),
                ('content', models.TextField(help_text='通知内容，支持变量替换', verbose_name='内容模板')),
                ('channel', models.ForeignKey(help_text='该模板使用的通知渠道', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='chewy_notification.notificationchannel', verbose_name='所属渠道')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
                'db_table': 'chewy_notify_template',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('success', '发送成功'), ('failed', '发送失败'), ('retry', '重试中')], default='pending', max_length=20, verbose_name='发送状态')),
                ('response', models.JSONField(default=dict, help_text='发送后的响应数据', verbose_name='响应信息')),
                ('send_time', models.DateTimeField(blank=True, help_text='实际发送的时间', null=True, verbose_name='发送时间')),
                ('error_message', models.TextField(blank=True, default='', help_text='发送失败时的错误信息', verbose_name='错误信息')),
                ('channel', models.ForeignKey(blank=True, help_text='使用的发送渠道', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='chewy_notification.notificationchannel', verbose_name='发送渠道')),
                ('target', models.ForeignKey(blank=True, help_text='接收通知的目标', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='chewy_notification.notificationtarget', verbose_name='通知目标')),
                ('template', models.ForeignKey(blank=True, help_text='发送时使用的模板', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='chewy_notification.notificationtemplate', verbose_name='使用模板')),
            ],
            options={
                'verbose_name': '通知记录',
                'verbose_name_plural': '通知记录',
                'db_table': 'chewy_notify_record',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['-create_time'], name='chewy_notif_create__b4e3ca_idx'), models.Index(fields=['status'], name='chewy_notif_status_6ed96d_idx')],
            },
        ),
    ]
